development:
  API_URL: 'http://localhost:9292/api/v1'
  SESSION_SECRET: 'replace_with_a_long_random_string_at_least_64_chars_long_xxxxxxxx'

test:
  API_URL: 'http://localhost:9292/api/v1'
  SESSION_SECRET: 'replace_with_a_long_random_string_at_least_64_chars_long_xxxxxxxx'

production:
  API_URL: 'https://api.example.com/api/v1'
  SESSION_SECRET: 'replace_with_a_long_random_string_at_least_64_chars_long_xxxxxxxx'
